alexellis/derek

- Dockerfile
- Makefile
- commentHandler.go
- commentHandler_test.go
- main.go
- permissionsHandler.go
- permissionsHandler_test.go
- test cases move into test functions
- break out method that returns error instead of log.Fatal
- add Makefile
> Refactoring and build fix

- .CUSTOMERS
Also sorted the list alphabetically
> Add "moby" to customers

- .CUSTOMERS
Thanks for providing this cool service!
> Add Subsurface-divelog to customers

- README.md
- commentHandler.go
- commentHandler_test.go
- main.go
Summary of changes:
Moved out handleComment code into separate functions.  
Added tests for new helper functions.  
Added edit title as an alias for set title
Updated README
Factored out log.Fatal
Altered main.go such that a http 500 is not longer seen when an unexpected X_Github_Event is received
Extracted constants to provide consistency between values used in parse and handleComment.
A test instance is running over on https://github.com/rgee0/Test.  This is hosted so should be always on
> Moved out handleComment code into separate functions.  Added edit title.

- auth/client_factory.go
- auth/customers.go
- auth/customers_test.go
- auth/hmac.go
- auth/isCustomer_test.go
- auth/jwt_auth.go
- commentHandler.go
- commentHandler_test.go
- main.go
- permissionsHandler.go
- permissionsHandler_test.go
- pullRequestHandler.go
- pullRequestHandler_test.go
- types/types.go
Due to unconvential forking of code without maintaining copyright
notices with at least one GitHub user this commit adds the header
in each .go source file to discourage "passing-off".
https://github.com/miekg/dreck
No-harm change, build and tests still run.
> Add license notice

- Dockerfile
Changed golang version in Dockerfile to build with
latest version of golang.
Updated Dockerfile with latest golang version.
This PR updates Dockerfile with golang:1.9.7-alpine from golang:1.9.6-alpine
It fixes issue https://github.com/alexellis/derek/issues/77.
Tested with 
```make build```
```faas-cli build -f derek.yml```
> Update golang version to latest - 1.9.7

- Dockerfile
With this commit Dockerfile golang version is updated to 1.10.3
Update to golang version 1.10.3-alpine
Update dockerfile to build from golang:1.10.3-alpine
This references https://github.com/alexellis/derek/issues/77.
Builded and pushed derek to my repo and did example command it worked.
> Update golang version build to 1.10.3

- .travis.yml
- build.sh
Build.sh file is added to build derek image with
necessary tags and extends .travis.yml to push the image
with the tags needed after successful build.
Add after_success to push images on release.
This change extends .travis.yml file to add after_success method in which
docker image is pushed to a image hub.Also build.sh file is added to build
the image with the needed tags.
It solves https://github.com/alexellis/derek/issues/76 .
Build successfuly derek with ```./build.sh``` and pushed to my repository by changing
the alexellis prefix with martindekov prefix in the places alexellis is mentioned in building
and pushing images.
> Extend .travis.yml to build with script and push image

- main.go
- main_test.go
- pullRequestHandler.go
- types/types.go
This commit adds contributing_url field to the .DEREK.yml file to point
to contribution guide.
Signed-off-by: Vivek Singh <vivekkmr45@yahoo.in>
Fixes: #87 
Test result and process added in comments below.
> Add contributing URL field to .DEREK.yml

- .CUSTOMERS
Signed-off-by: Edward Wilde <ewilde@gmail.com>
> Add ewilde to .CUSTOMERS file

- README.md
Add godoc badge to readme
closes #98 
N/A
> update README with godoc badge

- handler/commentHandler.go
- handler/commentHandler_test.go
- handler/permissionsHandler.go
- handler/permissionsHandler_test.go
- handler/pullRequestHandler.go
- handler/pullRequestHandler_test.go
- main.go
Move source code suffixed with Handler to package handler.
Add a new sub-level package.
It creates a new package to isolate derek api functionality. This is to move closer towards deploying derek as a function.
I refactored a local instance of the project to use package `handler`. I also added a local FaaS function to test the Handler package with.
I used faas-cli 0.7.7 to build and deploy the function.
This will require updating [main.go](https://github.com/alexellis/derek/blob/master/main.go) to use the handler package.
> add handler package

- Makefile
- README.md
- handler/commentHandler.go
- handler/commentHandler_test.go
- enables use of / as an alias for Derek commands all the time
whether configured or otherwise
- updates Makefile to run all unit tests, not just those in the
root main package
Closes #113 
Unit testing only
> Allow slash alias all the time

- main.go
- types/types.go
- throws error into logs when private repo detected
Related to better logging for #116 
Building the code only & CI
> Add Private repo flag

- GET.md
- handler/permissionsHandler.go
- main.go
Signed-off-by: Matias Pan <matias.pan26@gmail.com>
This PR adds support for private repositories. To support this we had to change the way we were fetching the `.DEREK.yml` config file, if the repo is private we use GitHub's API, if it's not then we default to the CDN.
In order to support fetching files from repositories that are private
a new function was added called GetPrivateRepoConfig. This function
uses GitHub's API to download the file instead of download it from
the CDN.
I thought it would be best to introduce a new function instead of
rewriting the current one and changing its signature. This is because
I wanted to make sure I wasn't breaking any existing functionality.
I built derek at `matipan/derek:privateRepos`, deployed it on my personal cluster and tested it using a private …
> Private repos support

- .CUSTOMERS
Signed-off-by: colin-mccarthy <colin@colin.mccarthy80501@gmail.com>
I have added my GitHub user name per the Get Derek instructions. I am excited to use Derek on my 
repo.
- [x ] My code follows the code style of this project.
- [x ] I've read the [CONTRIBUTION](https://github.com/alexellis/derek/blob/master/CONTRIBUTING.md) guide
- [x ] I have signed-off my commits with `git commit -s`
> Added my GitHub user name per the Get Derek instructions.

- .CUSTOMERS
added goreleaser to the customer list
> added goreleaser as customer

- Dockerfile
Adding app user in the dockerfile to run the code inside
the container instead of running it through the root folder
Signed-off-by: Martin Dekov <mvdekov@gmail.com>
The code is ran as app user instead of root
Closes #128 
1. Build with the new Dockerfile Derek image.
2. Exec in container and run `pwd`.
Derek from master:
Derek with the change:
Verified the bot is working in `push2` testing repo:
> Run derek as non root user

- build.sh
Signed-off-by: Keiran Smith <contact@keiran.scot>
Fixes error with docker build
Fixes docker build with Travis using DOCKER_NS
> Fix #129 Error building docker

- Dockerfile
Moving the building process to multi-stage
Signed-off-by: Martin Dekov <mvdekov@gmail.com>
Now the building process is with multi-stage with latest watchdog
Closes #127 
Build the dockerfile, pushed to dockerhub and tested e2e with the newest watchdog:
> Move to multi-stage build

- .CUSTOMERS
Signed-off-by: Cassiano Aquino <cassianoaquino@me.com>
This PR adds evilsocket user to the .CUSTOMERS file
We would like to use Derek for a small open source project that we are working to allow more individuals to help with triage of tickets and PRs.
The project mentioned is [pwnagotchi](https://github.com/evilsocket/pwnagotchi) it's a security-related project that brings AI to a portable network security testing platform.
Sadly there's no way for me to test this change.
The change does not fit any of the categories.
> add evilsocket do .CUSTOMERS

- .CUSTOMERS
Added csakshaug and dxcn to .CUSTOMERS
> Added csakshaug and dxcn to .CUSTOMERS

- .CUSTOMERS
Add okteto to Derek's customer list.
Add okteto to Derek's customer list
We want to use Derek's service in the okteto/okteto project
No tests required
> Add okteto tu customer list

- .CUSTOMERS
Add TheYkk to Derek's customer list
I want to test derek app
> Add TheYkk to customers

- README.md
Adding okteto to the users list in the README.
> add okteto to  the users list

- auth/jwt_auth.go
Github are moving an endpoint for access_tokens for github apps. This
moves to the new api url
Signed-off-by: Alistair Hey <alistair@heyal.co.uk>
> Update to call new github API

- handler/pullrequest_handler.go
- types/types.go
Adding check which determines whether or not
there are existing commits which are unsigned.
The check is determined by the no-dco label.
Adding succesful/failure check when unsigned commits are present in the PR
Adding check which is successful by default and when `no-dco` label is applied the check fails, when the commits are signed the check is again successful
I think the `allow merge if all checks pass` would be turned on in the GitHub UI. I have red something about required status checks or something
Fixes #95 
Also suggestions on the text, the content of the titles body etc. Would be appreciated!
Tested in repository [here](https://github.com/martindekov/push2/pulls)
> Note: I have local minikube instance exported with ngrok …
> Add fail check for dco

- .CUSTOMERS
Add k8spin organization to customer list
We would like to try out Derek on the https://github.com/k8spin organization
N/A
> Add k8spin organization

- Dockerfile
- go.sum
- handler/template_handler.go
- main.go
- types/types.go
Signed-off-by: Alex Ellis (OpenFaaS Ltd) <alexellis2@gmail.com>
Add required issue headings
Adds basic mechanism to help users understand that issue
templates are not optional. This is becoming a tiring and 
fatiguing task - asking users politely to follow the 
contributing guide and give the context we need to help 
them with issues.
All valid headings: https://github.com/alexellis/two-better-than-one/issues/5
One required heading deleted: https://github.com/alexellis/two-better-than-one/issues/7
https://github.com/alexellis/two-better-than-one/blob/master/.DEREK.yml#L46
This is an optional new feature, you need to add the following for it to come into action, the titles should be part of the project or repo's issue template:
```yaml
required_in_issues:
- "## Expected Behaviour"
- "## …
```
> Add required issue headings

- .CUSTOMERS
Signed-off-by: juandisay <info@juandisay.org>
> Try using Derek.

- .CUSTOMERS
Remove Okteto due to cancelled sponsorship
> Remove Okteto due to cancelled sponsorship
