alexellis/derek

.gitignore, Dockerfile, auth/jwt_auth.go, commentHandler.go, handler.go, main.go, types/types.go
Allows non-write-access users to add labels to issues and PRs.
Here's an example:
`Derek add label: skill/intermediate`
`Derek remove label: skill/intermediate`
ACL is a plaintext file called MAINTAINERS in the root of the GitHub repo.
MAINTAINERS:
```
alexellis
johnmccabe
```
=> Update to include label allocation

Dockerfile, README.md, auth/client_factory.go, auth/jwt_auth.go, commentHandler.go, handler.go
This PR sets the Derek Github Application ID via the `application`envvar. This ID is the one associated with the registered application, while the installation is associated the instance of Derek installed to your Github account.
Failing to set the correct id (ie the application ID) was causing the generation of JWT tokens to fail with an invalid permissions error, it had originally been hardcoded.
Have tested this here https://github.com/johnmccabe/webhook_test_delme/issues/1
=> Set the Github App ID via envvars

README.md, commentHandler.go, types/types.go
This PR adds commands for assigning and unassigning issues/PRs. For example:
```
Derek assign: johnmccabe
Derek unassign: johnmccabe
```
It also provides the shortcut `me` to assign/unassign the user making the comment:
```
Derek assign: me
Derek unassign: me
```
Note that the README has been updated, and the `parse()` function refactored.
This has been tested here - https://github.com/johnmccabe/webhook_test_delme/pull/2
=> Add assign and unassign commands

README.md, commentHandler.go
Added the ability for maintainers to close and reopen issues & PRs to address #9 
Also performed minimal update the README.md to include the new commands and add an updated `faas-cli deploy` command.
Tested on one of my own [repos] (https://github.com/rgee0/Test/pull/3) used for testing.
=> Added close and reopen commands. Fixes #9

README.md, permissionsHandler.go, permissionsHandler_test.go, types/types.go
This change adds "curators" as an alias to "maintainers" in the .DEREK.yml file.
Some users were finding the term confusing due to existing use of the term maintainers within their project. When we get to roles in Derek 2.0 that will go away, but for now this should make Derek easier to understand/install.
=> Add "curators" alias to .DEREK.yml file

Dockerfile, README.md, commentHandler.go, commentHandler_test.go, main.go, pullRequestHandler.go, pullRequestHandler_test.go, types/types.go
Fixes #21 
Fixes #24 
Fixes #15 
Fixes #28
Summary of changes:
* Added `go test` to Dockerfile.
* Added a check that the issue_comment webhook action isn't `deleted` before taking action, as this was causing Derek to re-trigger when comments originally aimed at Derek deleted.
* Added a check that the pull_request webhook action isn't `closed` before taking action, as this was causing Derek to perform the dco_check unnecessarily.
* Added tests to cover some of the pullRequestHander methods.
* Implemented `Derek set title:`, `Derek lock` & `Derek unlock` commands
* Updated `README.md` to cover new features, marking the lock & title features as complete and adding two additional features.
* Extracted a method in the open/close switch clause to assess requested state against current state and …
=> Set title / double action bug / pullRequest tests / lock issue

.gitignore, Dockerfile, GET.md, auth/client_factory.go, auth/hmac.go, auth/jwt_auth.go, commentHandler.go, main.go, pullRequestHandler.go, stack.yml
Fixes #41 
Derek will now read the symmetric and private keys from platform secrets.
Much of this change resides in the auth package which was using a combination
of files built in to the image and environment variables to achieve GitHub
authentication.  These have been replaced by /run/secrets/derek_private_key
and /run/secrets/derek_secret_key.
Also significantly updated GET.md
=> Add secret support for private_key and secret_key

README.md, permissionsHandler.go, permissionsHandler_test.go, types/types.go
this PR adds support for the optional `redirect` filed in `.DEREK.yaml` to allow jumping away from this config and loading another. the change is non-breaking for existing users.
spoke to @alexellis about this at KubeCon. :)
the idea is to allow multiple repos to use the same config file.
https://github.com/alexellis/derek/issues/58
pushed a test config to a github fork and added a temporary test in `permissionsHandler_test.go` (not included) that fetches the config from a redirected URL. then did a `go fmt`, `golint` and `go test -v` on the changes.
the best way to test this is to pull this branch and add this in the yaml:
```
redirect: <some-config-url>
```
=> Support the loading of config files via URL redirection

auth/client_factory.go, auth/jwt_auth.go, commentHandler.go, pullRequestHandler.go
Add in the ability to over-ride the private key path so that anyone
vendoring the auth package can use a private key outside of the
standard secret location as used by Derek himself.
In testing
=> [WIP] Add privateKeyPath param to MakeAccessTokenForInstallation

GET.md, auth/customers.go, auth/customers_test.go
The existing location of the .CUSTOMERS file is hard-coded which means
that anyone self hosting will need to either add an entry into the project
.CUSTOMERS, or alter the source code to point at their own location.
This change enables an over-ride of the default .CUSTOMERS location by
setting an `customers_url` environment variable.  The location should
be an `https` endpoint.
Test added for the new function which attempts to read the ENV var and
GET.md updated to include `customers_url` in the stack file section.
Tested a number of scenarios on a DigitalOcean machine.
* Ran in default mode and confirmed as functioning as intended
* Ran with `customers_url: https://raw.githubusercontent.com/rgee0/Test/master/.CUSTOMERS` which **didn't** …
=> [Merge/release] Accommodate custom .CUSTOMERS via ENV var

GET.md, commentHandler.go, derek.yml, main.go, pullRequestHandler.go, stack.example.yml
A new change upstream means there are two potential paths for
secrets depending on the version used. This covers the scenario
by implementing a mandatory secret_path config item.
#59 
Tested on GitHub / Swarm - bot created label correctly:
https://github.com/alexellis/store-gist/issues/2
This change was in progress by @rgee0 but I had to bring it forward for some testing @mrtind is working on via #68
=> Update key paths for OpenFaaS 0.8.3

pullRequestHandler.go, pullRequestHandler_test.go, types/types.go, types/types_test.go
I added function so new contributors could be recognized by
the community.
Adding simple function so new people who contribute to project could be recognized
by the community.
Added firstTImeContributor function that checks if the webhook author_association has NONE 
if it does then the contributor is new.Also extended pullrequest struct in types.go to include
AuthorAssociation since from what i saw the field is part of PullRequest field the webhook gives.
https://github.com/alexellis/derek/issues/65
It adds new contributors tag to newcomers.
I created test function in pullRequestHandler_test.go which passed. I also ran 
$ docker build -t derek .
which builded derek successfully.
=> Add label to people who contribute for the first time

main.go, main_test.go
We need to check if newlines are present in the file where
we load our docker secrets from.Some editors may add extra
newline at the end making the secret invalid.
Adding check to see if newlines are present in the file from which we 
create docker secret for derek-secret-key.
Add check in main.go if newline is present in the secret string loaded from the 
file and if so it removes it.
It solves issue #72.
=> Remove newlines from file where webhook secret is stored

commentHandler.go, commentHandler_test.go
Checks if the maintainer wants to remove no-dco label and if so it
prevents them from doing that.
Prevents maintainers to remove no-dco label with ```Derek remove label: no-dco```.
Added check if the label that the maintainer wants to remove is the ```no-dco``` and prevents them from removing it.
Closes #85 .
Opened PR without sign off here https://github.com/martindekov/push2/pull/14 and no-dco was applied.
comment:
```
Derek remove label: NO-DCO
```
response:
```
martindekov wants to remove label of 'NO-DCO' on issue #14 
martindekov the request is not allowed.Label `NO-DCO` can be removed by owner or by signing out the commit.
```
comment:
```
Derek remove label: no-dco
```
response:
```
martindekov wants to remove label of …
```
=> Prevent maintainers to remove the no-dco label

USER_GUIDE.md
Signed-off-by: Richard Gee <richard@technologee.co.uk>
Split USER_GUIDE examples into separate code blocks
Small typo correction
Although the guide is explicit in stating that multi-line instructions are not supported the examples may give the impression that they are.
No issue - trivial change.
Previewed the markdown
=> Split USER_GUIDE examples into separate code blocks

README.md, commentHandler.go, commentHandler_test.go
me and Martin collaborated on this change over a couple of Zoom meetings.
please, let me know if this needs any changes.
/cc @rgee0 @alexellis 
Track the environment variable `use_slash_trigger`
and make it possible to use `/` as the command trigger
that the bot uses instead of "Derek ".
- Update unit tests in commentHandler_test.go.
- Update README.md
Signed-off-by: Lubomir I. Ivanov (VMware) <neolit123@gmail.com>
https://github.com/alexellis/derek/issues/63
unit tests only on my side.
@mrtind and @ivanayov can possibly do an e2e if they have the setup.
=> Support slash as a command trigger

auth/customers.go, auth/customers_test.go, main.go, main_test.go
Setting the customer validation and hmac validation on by
default also moving customer validation into its own function
so it can be tested more easily and extending the tests
to showcase the logic the work was started by @ivanayov
This adds more secure experience for the user so the hmac and security validation should now be turned off intentionally with explicit `false` or `0`
Actually part of [#316](https://github.com/openfaas/openfaas-cloud/issues/316) issue in OpenFaaS Cloud
Unit tests
For derek users with authentication turned off if they move to the newest version, they should explicitly set the `validate_customers: 0/false` and `validate_hmac:0/false`
=> Turn on validate customers and hmac by default

USER_GUIDE.md, handler/pullRequestHandler.go, handler/pullRequestHandler_test.go, main.go, types/types.go
This commit adds a new feature for pr_content_check
This feature will verify that the incoming PR has
something in the description (aka body)
If there is no description, the invalid label will be applied
and a comment will be added to the PR with a link to the
contributing guide.
Signed-off-by: Burton Rheutan <rheutan7@gmail.com>
Resolves #103 
Unit tests added and passing
=> Add pr_content_check to features

handler/commentHandler.go, handler/commentHandler_test.go
This adds  support for comments like `Derek assign reviewer: username`.
Works only with a single reviewer for the moment.
Raised in issue [#48](https://github.com/alexellis/derek/issues/48)
Signed-off-by: Ivana Yovcheva <iyovcheva@vmware.com>
After updating the comment:
Unit tested
=> Add support for `assign reviewer`

README.md, USER_GUIDE.md
This adds usage instructions to the README
Signed-off-by: Ivana Yovcheva <iyovcheva@vmware.com>
N/A
=> Document assign reviewer feature

GET.md
Adding namespace when creating the secret since
the command was invalid and misleading
`kubectl` command which creates secrets for derek was invalid (the namespace was missing)
Adding default `openfaas-fn` namespace to the `kubectl` commands which created the two secrets
Didn't raise an issue due to the simplicity of the change
N.A.
=> Add namespace in secret creation

handler/pullRequestHandler.go, handler/pullRequestHandler_test.go
Signed-off-by: Matias Pan <matias.pan26@gmail.com>
This PR adds a check for when commits have an anonymous email address.
If at least one of the commits was signed with an email address that ends in `noreply.github.com` then we reply with a different comment that asks for the commit to be properly signed. This is comment that we are using(it can be changed :smile: ): 
> Thank you for your contribution. It seems that one or more of your commits have an anonymous email address. Please consider signing your commits with a valid email address. Please see our [contributing guide](https://github.com/matipan/test-derek/blob/master/CONTRIBUTING.md).
Unit tests for new functionality
I built derek at `matipan/derek:anonymousCheck`, deployed it on my personal cluster and tested it using the …
=> Check if commit was signed by an anonymous email

USER_GUIDE.md, handler/commentHandler.go, handler/commentHandler_test.go, stack.example.yml
Signed-off-by: Richard Gee <richard@technologee.co.uk>
This change enables multiple labels to be applied through a single comment, by allowing for a comma separated list to be provided.  Also added plural aliases for the labels commands.
This change also introduces a new env var which limits how many labels can be processed in a single command.  This defaults to 5 but can be set to preference through `multilabel_limit`.  An example has been included in the `stack.example.yml`. A test has been added for the function which retrieves this value from the env vars.
As the requested labels are pre-processed to ascertain which are actionable and which are not given the requested action, the limit will be applied to the first _n_ actionable labels, rather than the first _n_ requested labels.
As …
=> Add comma separated multi labels facility

GET.md, handler/pullRequestHandler.go
Signed-off-by: Richard Gee <richard@technologee.co.uk>
Amends references to `--sign-off` with `--signoff` as per git client help.
```
-s, --signoff
Add Signed-off-by line by the committer at the end of the commit log message. The meaning of a signoff depends
on the project, but it typically certifies that committer has the rights to submit this work under the same
license and agrees to a Developer Certificate of Origin (see http://developercertificate.org/ for more
information).
```
The message was wrong.  It's now correct.  Also updated the GET.md reference.
Trivial non-invasive change
=> Correct --sign-off to --signoff in bot feedback

USER_GUIDE.md, handler/commentHandler.go, handler/commentHandler_test.go, main.go, types/types.go
Adding messages option to the derek bot in order
to apply tempaltes or boilerplate things that we write
all the time.
Extending the comments handler, by passing the derek config file (`.DEREK.yml`), in order to take the `messages` field from it and pass it to the executing function which sends the message to the Issue.
Closes #109 
Manually multi line literal value of the message:
> Note in order for this to work, the string literal should be placed just below the `|` like so:
```
message:
- name: slack
value: |
--
Join Slack to connect with the community
https://docs.openfaas.com
```
> If we go like this, this will lead to parsing error
```
message:
- name: slack
value: |
--
Join Slack to connect with the community …
```
=> Add messages option

handler/commentHandler.go
Turning down the verbosity of the new messages feature
as it was too long. The commit removes the body of the
message leaving only the name of the message to be applied
Signed-off-by: Martin Dekov <mvdekov@gmail.com>
Response has the value of the message removed
The old response included the message content and its name, now it has only the message name.
Manually, the response is now:
On success:
On failure(the same):
=> Turn down the verbosity of the messages feature response

handler/pullRequestHandler.go, handler/pullRequestHandler_test.go, main.go
This change adds the new feature `hacktoberfest`
The goal of this feature is to find flyby pull requests
that are considered spam.
A pull request that is a first time contributor, not signed,
and only changing markdown (md) files is assumed to be spam.
If the contributor has read the contribution guide, they
would have signed their commit, and the handler would have
no affect.
Otherwise, the pull request is closed, and an invalid
label is added indicating that this PR should not be counted
Signed-off-by: Burton Rheutan <rheutan7@gmail.com>
Discussed with Alex via Slack
Added unit tests to verify the "markdown only" function works as expected. 
Unfortunately, I was unable to deploy and test as my deployment of Derek was not able to access the secret for some reason. I've run out of time …
=> Add Hacktoberfest feature

handler/release_handler.go, handler/release_handler_test.go
Add 1 min safety window for commit listing
building a new function includeCommits() based includePR()
which adds an 1 minute safety window for commit listing.
This will help Derek to avoid including commits from prior
releases.
Run `./build.sh` to run test cases and build Docker image
=> Add 1 min safety window for commit listing

Gopkg.lock, Gopkg.toml, USER_GUIDE.md, handler/permissions_handler.go, types/merge.go, types/merge_test.go, vendor/github.com/imdario/mergo/.gitignore, vendor/github.com/imdario/mergo/.travis.yml, vendor/github.com/imdario/mergo/CODE_OF_CONDUCT.md, vendor/github.com/imdario/mergo/LICENSE, vendor/github.com/imdario/mergo/README.md, vendor/github.com/imdario/mergo/doc.go, vendor/github.com/imdario/mergo/map.go, vendor/github.com/imdario/mergo/merge.go, vendor/github.com/imdario/mergo/mergo.go, vendor/github.com/imdario/mergo/testdata/license.yml
We can now provide some local overrides from our Local DEREK.yml,
these overrides are then merged with the remote DEREK.yaml.
This allows us to add specific users to specific repos, or add
features for specific ones too. Any slices are merged and the
single values are overridden by the local values.
Signed-off-by: Alistair Hey <alistair@heyal.co.uk>
#94 
Unit tests written, and this was tested on github using this repo: https://github.com/Waterdrips/heyal-ofc-customers
I setup a .DEREK.yml that had me as a contributor and a load of general config, but no "features"
pointed the Redirect at .DEREK-OVERRIDE.yml in the same repo, which added @alexellis as a contributor, plus it had the features listed.
Then I created a non signed commit and PR, DCO check was done (features in redirect file)
I …
=> Add ability to override/merge items in local .DEREK.yml

auth/jwt_auth.go, handler/pullrequest_handler.go
Github deprecated and api endpoint for auth tokens on apps, I previously
typed `apps/` and it should have been `app/`
This has been tested by running the broken container, verifying that it
did not work, then changing the `apps` to `app` and re-deploying - then
invoking a change on github that sent webhooks to my installation. After
the fix it worked, was given the 5k/hr rate limit and correctly added /
removed labels from PRs.
There are also some logging improvements and the wrong error was being used for one of the print statements.
Signed-off-by: Alistair Hey <alistair@heyal.co.uk>
#156 
see commit message and text above
=> Fix typo in removing deprecated api endpoint

handler/pullrequest_handler.go
Signed-off-by: Alex Ellis (OpenFaaS Ltd) <alexellis2@gmail.com>
Print verbose rate-limits
To help with #158 - if there is a low rate limit shown, then it may be that the client isn't authenticated.
Where possible, print rate limits along with the related
action in the GitHub API / SDK.
TBD
=> Print verbose rate-limits

.CUSTOMERS
Signed-off-by: Pascal Berger <pascal.berger@gmail.com>
Add cake-build to customer list
We would like to try out Derek on the https://github.com/cake-build/website repository.
N/A
=> Add cake-build to customer list

handler/permissions_handler.go, main.go, types/types.go
Pushing and opening this PR to override the PR https://github.com/alexellis/derek/pull/171
For context see https://github.com/alexellis/derek/pull/171
Tested deploying the Derek and configuring it.
- with private repo and public repo, using `master` branch as default and also using another branch name as default (in this case tested with `main` branch as default)
=> Use repo default branch
